### ISSUE TITLE
Can't install because of license test failure

### ISSUE THREAD

**Issue by abraxxa** [zostay/p6-DOM-Tiny#2]
When trying to install the module on a rakudobrewed 2017.06 it fails as below:

[ahartmai@ahartmai-nb:~$ ]$ zef install DOM::Tiny
===> Searching for: DOM::Tiny
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Searching for missing dependencies: Test::META
===> Searching for missing dependencies: META6
===> Searching for missing dependencies: JSON::Class, JSON::Fast
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
===> Testing: JSON::Fast:ver('0.9.2')
===> Testing [OK] for JSON::Fast:ver('0.9.2')
===> Testing: JSON::Name:ver('0.0.2'):auth('github:jonathanstowe')
===> Testing [OK] for JSON::Name:ver('0.0.2'):auth('github:jonathanstowe')
===> Testing: JSON::Marshal:ver('0.0.12'):auth('github:jonathanstowe')
===> Testing [OK] for JSON::Marshal:ver('0.0.12'):auth('github:jonathanstowe')
===> Testing: JSON::Unmarshal:ver('0.08')
===> Testing [OK] for JSON::Unmarshal:ver('0.08')
===> Testing: JSON::Class:ver('0.0.8'):auth('github:jonathanstowe')
===> Testing [OK] for JSON::Class:ver('0.0.8'):auth('github:jonathanstowe')
===> Testing: META6:ver('0.0.15'):auth('github:jonathanstowe')
===> Testing [OK] for META6:ver('0.0.15'):auth('github:jonathanstowe')
===> Testing: Test::META:ver('0.0.9'):auth('github:jonathanstowe')
# the following may make some diagnostics from the module itself
===> Testing [OK] for Test::META:ver('0.0.9'):auth('github:jonathanstowe')
===> Testing: DOM::Tiny:ver('0.3.3'):auth('github:zostay')
    # license ‘Artistic’ is not one of the standardized SPDX license identifiers.
    # please use use one of the identifiers from https://spdx.org/licenses/
    # for the license field or if your license is not on the list,
    # include a URL to the license text as one of the 'support' keys
    # in addition to listing its name.

    # Failed test 'License is correct'
    # at /home/ahartmai/.zef/store/Test-META.git/89a354323648cd4db71418f52a963cbaa4621898/lib/Test/META.pm (Test::META) line 98
    # Looks like you failed 1 test of 8

# Failed test 'Project META file is good'
# at /home/ahartmai/.zef/store/Test-META.git/89a354323648cd4db71418f52a963cbaa4621898/lib/Test/META.pm (Test::META) line 75
# Looks like you failed 1 test of 1
===> Testing [FAIL]: DOM::Tiny:ver('0.3.3'):auth('github:zostay')
Aborting due to test failure: DOM::Tiny:ver('0.3.3'):auth('github:zostay') (use --force-test to override)
  in code  at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/sources/58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 373
  in method test at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/sources/58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 351
  in code  at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/sources/58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 528
  in sub  at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/sources/58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 525
  in method install at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/sources/58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 631
  in sub MAIN at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/sources/B9B6B5F22DE3727E789C70B98CFB4A5030EE58D8 (Zef::CLI) line 152
  in block <unit> at /home/ahartmai/.rakudobrew/moar-2017.06/install/share/perl6/site/resources/51CBBF669DC3E87AEC5365E41AAF2A27E5880204 line 1

**Comment by zostay** [comment]
I haven't been able to reproduce this. Both my own testing and [Travis CI](https://travis-ci.org/zostay/p6-DOM-Tiny) show green and the Travis CI test even installs everything with `zef`.

**Comment by abraxxa** [comment]
You've already fixed this in https://github.com/zostay/p6-DOM-Tiny/commit/d80bd9eeb344d3b4292be5066ee6af275a4daae7 but the lastest released version 0.3.3, which gets downloaded by zef, is older than the fix. Please release a new version.
