### ISSUE TITLE
Test fails on latest rakudo

### ISSUE THREAD

**Issue by 0racle** [zostay/p6-DOM-Tiny#4]
Failure occurs in `050-dom-more-pseudo-classes.t`.

```
~/p6-DOM-Tiny (git)-[master] # perl6 -Ilib t/050-dom-more-pseudo-classes.t
ok 1 - found all odd li elements
ok 2 - found all odd li elements
ok 3 - found all odd li elements
ok 4 - right tag
ok 5 - right text
ok 6 - right tag
ok 7 - right text
ok 8 - right tag
ok 9 - right text
ok 10 - right tag
ok 11 - right text
Cannot assign to a readonly variable ($/) or a value
  in block  at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 401
  in method equation:sym<function> at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 398
  in regex equation:sym<function> at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 267
  in regex equation at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 263
  in regex pseudo-class:sym<nth> at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 243
  in regex pseudo-class at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 241
  in regex selector:sym<pseudo-class> at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 233
  in regex selector at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 227
  in regex node-match at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 225
  in regex joiner at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 214
  in regex TOP at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 212
  in sub _compile at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 442
  in method select at /root/p6-DOM-Tiny/lib/DOM/Tiny/CSS.pm6 (DOM::Tiny::CSS) line 425
  in method find at /root/p6-DOM-Tiny/lib/DOM/Tiny.pm6 (DOM::Tiny) line 977
  in block <unit> at t/050-dom-more-pseudo-classes.t line 34
```

Issue appears to be related to a bug fix mentioned by Zoffix on Twitter [here](https://twitter.com/zoffix/status/921761704115101698). For the Twitter allergic, I have replicated the tweet (and associated comments) below:

> Rakudo Perl6 bug fix alert ⚠️⚠️⚠️
> If you `.match` or `.subst` in grammar actions that use `$/` as param, it's possible now that code will throw
> 
> ```perl6
> grammar { token TOP { $<test>=(.+) } }.parse: "wrong", actions => class {
>     method TOP($/) {
>         say $<test>;
>         say "correct".subst: /$<test>=(.+)/, { $<test>.uc }
>     }
> }
> # OUTPUT:
> # ｢wrong｣
> # WRONG
> # (this is old output, now it throws complaining about readonly $/)
> 
> # Correct way to write it: don't use $/ for parameter name
> grammar { token TOP { $<test>=(.+) } }.parse: "wrong", actions => class {
>     method TOP($match) {
>         say $match<test>;
>         say "correct".subst: /$<test>=(.+)/, { $<test>.uc }
>     }
> }
> # OUTPUT:
> # ｢wrong｣
> # CORRECT
> ```
> 
> A bunch of regex methods set caller's `$/`, so if you already have it as param in actions method, that causes conflict.
> 
> In past, this silently failed and as shown above, produced incorrect results. Now it will throw, complaining about readonly `$/`
> 
> To fix: don't use `$/` as param name or, better yet, restructure your grammar so you don't need to do any regexes in actions.

**Comment by zostay** [comment]
Fixed. *grumble grumble*
