### ISSUE TITLE
Do not pollute namespace by default

### ISSUE THREAD

**Issue by zoffixznet** [zostay/p6-DOM-Tiny#5]
Simply `use`ing the module [imports a bunch of symbols](https://github.com/zostay/p6-DOM-Tiny/blob/e9333d1a95cfaf742ef6dafb042c09ee8217e8ab/lib/DOM/Tiny.pm6#L7-L11). 

Currently this behaviour introduces conflicts with other code. e.g.:

```
$ perl6 -e 'use Text::Markdown; use DOM::Tiny'
===SORRY!=== Error while compiling -e
Cannot import symbol Text from DOM::Tiny, because it already exists in this lexical scope
at -e:1
------> use Text::Markdown; use DOM::Tiny⏏<EOL>
```

These symbols should not be exported by default. I recommend putting them under an export tag that isn't `DEFAULT` or better yet, prefexing them with `DOM::Tiny::` namespace.

**Comment by zostay** [comment]
This was fixed in a793a3fca31cd0f04ec01fbbab03b48c10130649, which has been released for some time. I forgot to mention the ticket and or come back here and close it. Whoops.
