### ISSUE TITLE
Answer to question in code

### ISSUE THREAD

**Issue by zoffixznet** [zostay/p6-DOM-Tiny#9]
Spotted [this comment](https://github.com/zostay/p6-DOM-Tiny/blob/7d258aa96cd63ef6746943af9f85a891ecbbd20d/lib/DOM/Tiny/HTML.pm6#L63) in code:

```perl6
{ $ = $<start> } # Why does this fix the regex?
```

I suspect the "broken" version didn't have the right value in `$<start>`, right? You can fix it with just an empty block, and the reason it fixes it is because starting a block updates the `$/` variable (updating it all the time would be too resource consuming, so it only gets updated at predefined "checkpoints")

**Comment by zostay** [comment]
Sounds like a Rakudo Bug to me. If starting a block updates `$/`, then so should an interpolated string.

**Comment by zostay** [comment]
Then plain usages should cause an update as well. 

IMO having implicit updates that happen in the background sometimes but not others in usage guarantees bugs that will frustrate end-users into switching to another language.

**Comment by zostay** [comment]
Laziness is fine, but there has to be a way to guarantee eagerness when you need it.

**Comment by zostay** [comment]
And then it has to be documented and explained very clearly that $<> inside of a regex doesn't necessarily mean what you think it means.

**Comment by zostay** [comment]
IMO either $<x> should always do what's expected or it should be an error. Otherwise, you're just causing confusion.
